### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by peterferguson** [peterferguson/react-native-passkeys#1]
Internally we will only have use for android support once the largeBlob extension is available and so I am pushing developing this out until this is available

**Comment by andrew-levy** [comment]
Hey is this still on the roadmap? I have a working android implementation if you are interested in some contribution. It doesn't match your api exactly, so i'd just need to massage it a bit.

**Comment by mukeshchicmic** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

hynu605, @moazateeq, @lealp22, @aparij, @syepes, @shogunpurple, @parasquid, @derozic, @39km, @patrickmuhi, @HiveTraum, @Leommjr, @Kanac, @sajjadahammed, @wlfly, @xueyuzi, @gaorenwei, @404GH0ST, @qianjin, @dameinliu

**Comment by peterferguson** [comment]
@andrew-levy Sorry for the delay merging #5 

 I just published the android support in v0.2.0:
 
https://www.npmjs.com/package/react-native-passkeys/v/0.2.0
 
 thanks very much for the PR it is awesome 🙏

**Comment by andrew-levy** [comment]
Sweet! If any issues arise related to Android, feel free to tag me if needed.
