### ISSUE TITLE
Can't seem to link application identifier and associated domains

### ISSUE THREAD

**Issue by salieflewis** [peterferguson/react-native-passkeys#17]
`[Error: The operation couldn’t be completed. Application with identifier FAKETEAMID.ph.river.app is not associated with domain vono-aasa-production.up.railway.app]`

I am hosting a verified AASA file at the provided domain. And that JSON looks like this:
```{
  "applinks": {
    "details": [
      {
        "appIDs": [
          "FAKETEAMID.ph.river.app"
        ],
        "components": [
          {
            "/": "/*"
          }
        ]
      }
    ]
  },
  "webcredentials": {
    "apps": [
      "FAKETEAMID.ph.river.app"
    ]
  }
}
```

From my understanding `FAKETEAMID` is automatically configured by Expo in development environments. I'm confused about how this is being overriden in the example app. Thank you in advance!

**Comment by peterferguson** [comment]
Hey you can set the bundle identifier in the app config by following [the expo docs](https://docs.expo.dev/versions/latest/config/app/#bundleidentifier)

We do it in the example for iOS & Android with this variable 
https://github.com/peterferguson/react-native-passkeys/blob/e7ee0230f75bde77ae1739547bcf83a663cb9b48/example/app.config.ts#L7

If you set these correctly that should resolve the issue! 

Going to close this but if you have any problems feel free to reach out

**Comment by salieflewis** [comment]
> Hey you can set the bundle identifier in the app config by following [the expo docs](https://docs.expo.dev/versions/latest/config/app/#bundleidentifier)
> 
> We do it in the example for iOS & Android with this variable
> 
> https://github.com/peterferguson/react-native-passkeys/blob/e7ee0230f75bde77ae1739547bcf83a663cb9b48/example/app.config.ts#L7
> 
> If you set these correctly that should resolve the issue!
> 
> Going to close this but if you have any problems feel free to reach out

My issue was surrounding the fact that the AASA file I was serving had been cached on Apple's servers. So the updates I was making to it weren't being reflected.

**Comment by peterferguson** [comment]
This is just configured during the `expo prebuild` or `eas build` step depending on how you are setting up your app.

I am not really sure what issue you are having anymore though. Do you maybe have an open repo I could look at?

**Comment by salieflewis** [comment]
I don't unfortunately, the project I am working on is currently private. The issue is essentially that in the context of the iOS simulator, it seems that the Development Team is set to be `FAKETEAMID`, so in the AASA file I'm hosting, I'm providing that in conjunction with my bundle identifier, and that seems to resolve issues developing locally.

For an internal distribution build, I needed to include my actual Development Team Id in the AASA file, as instructed in the docs. Essentially it is still unclear to me why or where the notion of `FAKETEAMID` is coming from. I don't think this is an issue with this module, just a larger Expo thing that I anticipated you may have run up against.

**Comment by peterferguson** [comment]
Ohhhhhhhh I see now

`FAKETEAMID` is just a placeholder in the docs!

You should change this out for your team id value & that value should be the same as the one in your AASA file

The team id should look something like the `Y37LU57238` you mentioned above

**Comment by salieflewis** [comment]
Sorry to keep this going, and appreciate you helping me. Where in the docs is there a reference to `FAKETEAMID`? I'm still confused about where in my code I would actually provide my Development Team Id.
