### ISSUE TITLE
Android Setup Issues

### ISSUE THREAD

**Issue by yashsisodiya** [peterferguson/react-native-passkeys#19]
ERROR  create error [Error: androidx.credentials.exceptions.domerrors.SecurityError@d37e6d3]

**Comment by peterferguson** [comment]
Hey not really sure how I can help if you just post there error and nothing else.

A [quick google search](https://stackoverflow.com/questions/76578743/unable-to-register-for-authentication-using-passkey-on-android) seems to suggest that you haven't properly setup the `rp.id` field

Going to close this feel free to reopen with a more reproducible error if you keep running into this

**Comment by erickriva** [comment]
@yashsisodiya Did you manage to make it work?
