### ISSUE TITLE
Is it customary to store the credential id on the server?

### ISSUE THREAD

**Issue by salieflewis** [peterferguson/react-native-passkeys#23]
I'm aware this isn't exactly an issue. Would be great to maybe have a discussion section for this repo. But yes, as the title suggests, I noticed in the example app that the credential id is stored in state. In a production implementation is the custom to store the credential id of the user's passkey on the server, and then fetch it directly before the authentication step?

**Comment by salieflewis** [comment]
This seems to suggest https://arc.net/l/quote/mkytijat but if anyone wants to provide any color, that would be great. Thanks!

**Comment by peterferguson** [comment]
Hey sorry for taking so long to get back to you! 

Yes in the majority of cases you want to store the credentialId on the server. The example was used state for simplicity for a proper implementation I would recommend either [using](https://authjs.dev/getting-started/providers/passkey) or looking at the [implementation of auth.js](https://github.com/nextauthjs/next-auth/pull/8808)
